engines:
  # ... CONFIG CONTENT ...
  phpcodesniffer:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
# ... CONFIG CONTENT ...

## other configuration excluded from example...
exclude_patterns:
  - "tests/"
  - "spec/"
  - "**/vendor/"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "resources/lang/"
  - "public/index.php"
